### ISSUE TITLE
Question about creating EPI reference

### ISSUE THREAD

**Issue by zqsha** [kenshukoiso/Whole_Brain_Project#2]
Hi experts,
Thanks for sharing this amazing dataset. I just have a couple of questions when I read the scripts for m01_start_bias_field.sh, m02_denoise_me.sh and m03_regist_ANAT2EPI.sh. These scripts already showed very detailed information about how to get results, however, I just wanted to make sure about some variables without annotations.

**Question 1: In the f02_average_run.sh, Line 19: fslmaths $1 -mul 2000 $1 -odt short**
Because this "$1" is not indicated, so I am not sure what it refers to. However, I noticed that the output file is not used in the follow-up analysis. So, can I ignore this command?

**Question 2: In the m01_start_bias_field.sh, Line 6: cp $1 uncorr.nii**
Even though "$1" is not specified in the script, I guess "$1" this variable refers to the T1w.nii generated from f03_BOCO.sh. Am I correct?

**Question 3: In the m02_denoise_me.sh, Line 3, DenoiseImage -d 3 -n Rician -i $1 -o denoised_$1**
Despite the "$1" is not specified in the script, but I guess this variable refers to the bico_T1w.nii, which is generated by Bias_field_script_job.m. Is it correct?

**Question 4: In the m03_regist_ANAT2EPI.sh, Line 12, antsRegistration**
This command line employed two important files, including EPI.nii and ANAT.nii. Even though both files do not have context in the script. But, based on the description in the paper, this **EPI.nii** file should refer to the denoised image generated from m02_denoise_me.sh. This **ANAT.nii** could refer to the defaced images generated by a02_deface_me.sh. Is it correct?
Also, this command line also used an initial matrix (i.e. initial_matrix.txt) to perform the initial moving transform. I am just curious about how to get this matrix if we run this antsRegistration with our own data. 

Thank you so much for your comments. Looking forward to your reply.

Best,
Cain

**Comment by kenshukoiso** [comment]
Hi Cain,

Thank you for reaching me out. And I am sorry again for my late response. 

Q1:
I think we used this just for changing data value and type. You can ignore this line. Though, if the following lines don’t work, use this line. If I remember correctly, some program needed specific type. 
Also, except for creating a reference file from nulled data, you don’t even have to run this script if you want to use individual run data. Just note that if you want to average across runs, it is recommended to average before BOCO to reduce interpolations on the data. 

Q2:
Yes, you’re right. We used bias correction to EPI T1w image (mean image of VASO image).

Q3:
Yes, also correct. To make a reference of image in EPI space, we used VASO (nulled) image with bias correction and denoising. 

Q4:
Yes, you’re right about ANAT.nii and EPI.nii. sorry about the lack of context. We simply changed the name of the files when analysing it.

To create initial matrix, you can use ITK-snap. You can follow this very nice tutorial from Renzo:
https://www.youtube.com/watch?v=bvIaqIGqwJI
Moreover, if you are intended to run antsRegistration in high-reso data, it is also important decision whether you use masks or not besides many registration parameters you can choose. We experienced that sometimes registration without mask had better registration result than with mask depends on the quality of the mask. For this, you will probably have to test-retest the registration to see which way has better results. 

I hope these provided you enough information. If you have further questions, please let me know. Personally, I have started my new position as of this April and I mostly focus on the current project now. Furthermore, I did this whole-brain work a little long time ago. So I have to remember at some point. Thus, it might take a lot of time to reply but I will reply to you as soon as I can. 

Best regards,
Kenshu

**Comment by zqsha** [comment]
Hi Kenshu,
Thank you so much for your reply. These comments are very helpful. I just wanted to double check the second question. So, this EPI reference image is generated by the mean motion and BOLD-corrected VASO images. Is it correct?

In the f03_BOCO.sh script, Line 36, it indicates that
echo "calculating T1 in EPI space"
3dTcat -prefix combined.nii  moco_nulled.nii moco_notnulled.nii -overwrite
3dTstat -cvarinv -overwrite  -prefix T1w.nii combined.nii

It seems that you first combined motion-corrected VASO and BOLD images, resulting in a combined.nii. And then, perform "cvarinv" function with the combined.nii, which is similar to the procedure correcting for BOLD signal on a VASO image. Finally, this T1w.nii is used for the follow-up bias field correction.

If I understand incorrectly, please correct me. Thanks again for your reply. I really appreciate it.

Best,
Cain

**Comment by kenshukoiso** [comment]
Hi Cain,

I believe the line you referred to was for calculating tSNR. (Sorry for the confusion in the print text…🙈) 
We just used VASO.Mean.nii from the piloting session for EPI reference (T1w EPI). 
Also in our preprint: “As an EPI reference image for later layerification, we used the run-average T1-weighted EPI scan (Grappa 6 (3×2) with fat saturation) from the sequence comparison sessions (No. 1).”

I hope this helps you. 
And thank you again for your interest in our data/pipeline!

Best regards,
Kenshu

**Comment by zqsha** [comment]
Hi Kenshu,
Thank you so much for your reply. Yes, I agree with you. That makes sense. So, the T1w.nii generated by f03_BOCO.sh script is used for other analyses, but not for the bias field correction. So, we just need to average the VASO images (no motion or BOLD correction) to get a VASO_mean.nii. This VASO_mean.nii will be used for bias field correction.

The reason why I am confused is that there is a "T1 EPI" under the "VASO_LN.nii" in this workflow. I have thought we need to use the motion and BOLD-corrected VASO images to generate this T1 EPI file. But, now I understood that this T1 EPI is not generated by the VASO_LN.nii, it's generated by additional VASO scans. 
![image](https://github.com/kenshukoiso/Whole_Brain_Project/assets/27337033/9ce1764e-9413-47a3-a229-80b68929ec40)

If I understand incorrectly, please correct me. It's a very detailed and amazing pipeline. Every step makes a lot of sense.

I have another question about s01_freesurfer_1st.sh, Line 21,
recon-all -s S8 -i S8_ref/ANAT.nii -all -hires -openmp 4 -parallel -wsthresh 75 -norandomness -expert ./expert.opts

The ANAT.nii is the image that is used for registration with EPI.nii. Is it correct?
While expert.opts is not indicated, based on the background knowledge of Freesurfer, I guess this file should at least contain "mris_inflate -n 100". But, I am not sure whether we need to specify other functions in this expert.opts. Thanks.

Best,
Cain

**Comment by kenshukoiso** [comment]
Hi Cain,

I think there’s still confusion. VASO.Mean.nii is generated by volume-wise mean from VASO function data, which is motion and BOLD corrected. In the flow chart, we simply renamed VASO.Mean.nii to T1 EPI.

For freesurfer question, yes, we used anat.nii in EPI space (registered in function space).
And you’re right about the expert option. For us, the following command is included. “mris_inflate -n 50” 

Best regards,
Kenshu

**Comment by zqsha** [comment]
Hi Kenshu,
Thank you so much for your reply. That makes sense. I computed the VASO.Mean.nii by averaging all of the motion and BOLD-corrected VASO images. However, I found the noise outside the brain is a bit annoying (please see below). The noise could affect the follow-up registration with the anatomical image. Even though I performed the bias field correction (m01_start_bias_field.sh) and denoise (m02_denoise_me.sh) on this VASO.Mean.nii, the noise outside the brain remains. 
I just remember LN_MP2RAGE_DNOISE can remove the noise outside the brain in the MP2RAGE image. But, I am not where LAYNii has additional functions to run denoise on the VASO images. Do you have any suggestions? Thank you so much in advance.
![image](https://github.com/kenshukoiso/Whole_Brain_Project/assets/27337033/16a91744-fea5-46ba-8f0d-745b882a1075)

Best,
Cain

**Comment by kenshukoiso** [comment]
Hi Cain,

If you only want to remove the noise from the outside of the brain, maybe you can consider making a whole-brain mask and multiply it to the noisy image? Otherwise, I think you can also consider using skull-strip. It might work.

I don't know if LN_MP2RAGE_DNOISE can be used for VASO data. For this, I would recommend asking LayNii experts. Though I think either masking out or skull strip works.

Good luck with it!

Best regards,
Kenshu

**Comment by zqsha** [comment]
Hi Kenshu,

Yes, creating a brain mask is a really great idea to remove the noise outside the brain. I find it's working now. Thank you so much for your valuable suggestions/comments!

Best,
Cain

**Comment by kenshukoiso** [comment]
Hi Cain,

My pleasure:)
Good luck with your further analysis!

Best regards,
Kenshu
